language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.5
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
    - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml